language: node_js
node_js:
  - "stable"
cache:
  directories:
  - backend/node_modules

branches:
  only:
    - master
    - dev
    - teste-travis
script:
  - npm run build

  

#deploy:
 # provider: pages
 # skip-cleanup: true
 # github-token: $GIT_TOKEN  # Set in travis-ci.org dashboard, marked secure
 # local_dir: build
 # keep-history: true
 # on:
 #   branch: master
