name: Backend - DEV - Build
on:
 push:
   branches:
     - main
     - dev
defaults:
  run:
    working-directory: ./backend
jobs:
 build:
   name: Build
   runs-on: ubuntu-latest
   strategy:
     matrix: 
       node-version: [14.x]
   steps:
   - uses: actions/checkout@v2

   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v2
     with:
       node-version: ${{ matrix.node-version }}  
       
   - name: Install Packages
     run: npm install
     
   - name: Build jobi backend
     run: node server.js
     
   - name: Upload production-ready build files
     uses: actions/upload-artifact@v2
     with:
       name: production-files
       path: ./build
